### Get All Pegawai
GET http://localhost:5000/pegawais
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9wZWdhd2FpIjo0LCJuYW1hX3BlZ2F3YWkiOiJLYW5pYSIsImVtYWlsIjoia2FuaWFAZ21haWwuY29tIiwicHJvZGkiOiJUZWtuaWsgSW5mb3JtYXRpa2EiLCJzdGF0dXMiOiJBa3RpZiIsImlhdCI6MTc1MDMyMTU4MSwiZXhwIjoxNzUwMzIxNjAxfQ.HitVSHf8mTB05OWR1KNiugnDmIPyFvl8DRRnyce8qrk

### Get Pegawai by ID
GET http://localhost:5000/pegawais/6

### Get All Role
GET http://localhost:5000/roles

### Get Role by ID
GET http://localhost:5000/roles/1

### Get All Periode
GET http://localhost:5000/periode

### Get All Jenis Audit
GET http://localhost:5000/jenis-audit

### Get All Role Pegawai
GET http://localhost:5000/role-pegawai

### Get All Role Pegawai
GET http://localhost:5000/pegawais-data

### Get Role Pegawai By Id
GET http://localhost:5000/role-pegawai/1

###
# Create Jenis Audit
POST http://localhost:5000/jenis-audit
Content-Type: application/json

{
    "nama_jenis": "TW1",
    "created_by": 1
}

###
# Create Periode
POST http://localhost:5000/periode
Content-Type: application/json

{
    "nama_jenis": "TW1",
    "created_by": 1
}

###
# Create Periode
POST http://localhost:5000/pegawais
Content-Type: application/json

{
    "nama_pegawai": "Linda",
    "email": "linda@gmail.com",
    "password": "123",
    "confPassword": "123",
    "prodi": "Sistem Informasi",
    "status": "Aktif"
}

###
# Registrasi Pegawai
POST http://localhost:5000/pegawais
Content-Type: application/json

{
    "nama_pegawai": "Hilwa",
    "email": "hilwa@gmail.com",
    "password": "123",
    "confPassword": "123",
    "prodi": "Teknik Industri",
    "status": "Aktif"
}

###
# Create Pegawai
POST http://localhost:5000/pegawais
Content-Type: application/json

{
    "nama_pegawai": "Linda",
    "email": "linda@gmail.com",
    "password": "123",
    "confPassword": "123",
    "prodi": "Sistem Informasi",
    "status": "Aktif"
}

###
# Create Role Pegawai
POST http://localhost:5000/role-pegawai
Content-Type: application/json

{
  "id_pegawai": 2,
  "id_role": 2
}

###
# Update Role Pegawai
PATCH http://localhost:5000/role-pegawai/2
Content-Type: application/json

{
  "id_role": 4
}


###
# Update Pegawai
PATCH http://localhost:5000/pegawais/1
Content-Type: application/json

{
  "nama_pegawai": "Talia",
  "email": "taliaaa@gmail.com",
  "prodi": "Sistem Informasi",
  "status": "Aktif"
}

###
# Update Profile Pegawai
PATCH http://localhost:5000/profile/2
Content-Type: application/json

{
  "nama_pegawai": "Nanda Kharisma",
  "email": "nandaaa@gmail.com"
}


###
# Delete Pegawai
DELETE http://localhost:5000/pegawais/4

###
# Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "talia@gmail.com",
  "password": "123",
  "selectedRole": "Admin LPMPP"
}

###
# Token Baru
GET http://localhost:5000/token

### 
# Logout
DELETE http://localhost:5000/logout